.github/workflows/alpha.yml, .github/workflows/main.yml, node/src/chain_spec.rs, node/src/command.rs
For example:
- Feature
- Bug
- Refactor …
=> Renamed chain spec name

.github/workflows/alpha.yml, .github/workflows/beta.yml, .github/workflows/main.yml, .github/workflows/release-candidate.yml, .github/workflows/release.yml
=> CI/CD: use bastion for deploy

.maintain/docker/injected-binnary.Dockerfile
For example:
- Feature
- Bug
- Refactor …
=> CI/CD: added libssl1.1 and ca-certificates

node/src/chain_spec.rs
For example:
- Feature
- Bug
- Refactor …
=> Fixed era reward

.github/workflows/alpha.yml, .github/workflows/beta.yml, .github/workflows/main.yml, .github/workflows/release.yml
- [ MYR-1229] https://blocksphere2020.atlassian.net/browse/MYR-1229
=> CI/CD - improve skip deployment

.github/workflows/alpha.yml, .github/workflows/beta.yml, .github/workflows/main.yml, .github/workflows/publish-draft-release-candidate.yml, .github/workflows/publish-draft-release.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml
- [ MYR-1213] https://blocksphere2020.atlassian.net/browse/MYR-1213
=> CI/CD - fixed publish draft release

.github/workflows/alpha.yml, .github/workflows/beta.yml, .github/workflows/main.yml, .github/workflows/release.yml
- [ MYR-1213] https://blocksphere2020.atlassian.net/browse/MYR-1213
=> MYR-1213: CI/CD - fixed chain-spec.json

Cargo.lock, Cargo.toml
For example:
- Feature
- Bug
- Refactor …
=> Added patch to octopus-network

.github/workflows/deployer.yml, .github/workflows/tester.yml
For example:
- Feature
- Bug
- Refactor …
=> CI cleanup

.github/workflows/builder.yml, .github/workflows/tester.yml, Cargo.lock, node/src/chain_spec.rs, runtime/src/lib.rs
- Update octopus pallets by run `cargo update -p pallet-octopus-appchain`
- Bump spec implementation version
- Use fixed rust toolchain `nightly-2021-11-01`
- Feature
=> Updated octopus pallets v0.9.12

.github/workflows/builder.yml
- [MYR-1769 ] https://blocksphere2020.atlassian.net/browse/MYR-1769
Upload wasm file to discord
=> Upload wasm file to discord

.github/workflows/deployer.yml
For example:
- Feature
- Bug
- Refactor …
=> add jobs permission

pallets/server/src/benchmarking.rs, pallets/server/src/lib.rs, pallets/server/src/weights.rs
For example:
- Feature
- Bug
- Refactor …
=> Added new function

.maintain/benchmark.sh, Cargo.lock, node/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
For example:
- Feature
- Bug
- Refactor …
=> chore: bump verison

pallets/server/src/benchmarking.rs, pallets/server/src/interface.rs, pallets/server/src/lib.rs, pallets/server/src/tests.rs, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/tests.rs
For example:
- Feature
- Bug
- Refactor …
=> Refactor pallet server

pallets/server/src/benchmarking.rs, pallets/server/src/interface.rs, pallets/server/src/lib.rs, pallets/server/src/tests.rs, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/tests.rs
For example:
- Feature
- Bug
- Refactor …
=> Change server id from hash to string

.editorconfig, .rustfmt.toml, Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, pallets/tipping/benchmarking/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
For example:
- Feature
- Bug
- Refactor …
=> Bump version to 2.0.1

Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, pallets/tipping/benchmarking/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
For example:
- Feature
- Bug
- Refactor …
=> chore: bump version to 2.1.0

.github/workflows/builder.yml, .github/workflows/tester.yml
- [MYR-1966]
- improve paths-ignore tester pipeline
- add retag docker image condition
[MYR-1966]: https://blocksphere2020.atlassian.net/browse/MYR-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> improve tester add retag docker image condition

pallets/server/src/benchmarking.rs, pallets/server/src/interface.rs, pallets/server/src/lib.rs, pallets/server/src/tests.rs, pallets/server/src/weights.rs, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/src/tests.rs
For example:
- Feature
- Bug
- Refactor …
=> Added api url in server pallet

pallets/server/src/benchmarking.rs, pallets/server/src/interface.rs, pallets/server/src/lib.rs, pallets/server/src/tests.rs, pallets/server/src/weights.rs, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/src/tests.rs
For example:
- Feature
- Bug
- Refactor …
=> Added new field in server pallet

pallets/tipping/src/impl_tipping.rs, pallets/tipping/src/interface.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/types.rs
For example:
- Feature
- Bug
- Refactor …
=> Improved code

.github/workflows/deployer.yml
=> CI: improve deployment

pallets/tipping/src/functions/api_call.rs, pallets/tipping/src/functions/helper.rs, pallets/tipping/src/functions/unsigned_call.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/types/api_response.rs, pallets/tipping/src/types/payload.rs
For example:
- Feature
- Bug
- Refactor …
=> Fixed verify social media

pallets/tipping/src/functions/api_call.rs, pallets/tipping/src/functions/helper.rs, pallets/tipping/src/functions/unsigned_call.rs
For example:
- Feature
- Bug
- Refactor …
=> Fixed offchain worker when connect account

Cargo.lock
Enabling Cross-chain Token Transfer, so that all Networks can use other Token from Different networks;
Jira Link
https://blocksphere2020.atlassian.net/browse/MYR-2196
- Feature
- Bug
- Refactor
- Test
- Documentation
=> feat: bump octopus pallet

Cargo.lock, node/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
For example:
- Feature
- Bug
- Refactor …
=> chore: bump version to 2.1.2

.github/pull_request_template.md, .github/workflows/builder.yml, .github/workflows/create-tags.yml, .github/workflows/deployer.yml, .github/workflows/release.yml
- [MYR-2248]
create tag, remove development environment, change pull request template
- Feature
- Bug
- Refactor
- Test
- Documentation
- CI
[MYR-2248]: https://blocksphere2020.atlassian.net/browse/MYR-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: improve ci-cd

.github/workflows/builder.yml, .github/workflows/create-tags.yml, .github/workflows/deployer.yml, .github/workflows/release.yml, .github/workflows/tester.yml
=> style: code formatting

Cargo.lock, node/Cargo.toml, node/src/chain_spec.rs, node/src/cli.rs, node/src/command.rs, node/src/lib.rs, node/src/rpc.rs, node/src/service.rs, pallets/server/Cargo.toml, pallets/server/src/lib.rs, pallets/server/src/mock.rs, pallets/server/src/tests.rs, pallets/server/src/types.rs, pallets/tipping/Cargo.toml, pallets/tipping/benchmarking/Cargo.toml, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/benchmarking/src/mock.rs, pallets/tipping/src/impl_tipping.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/mock.rs, pallets/tipping/src/types.rs, runtime/Cargo.toml, runtime/src/lib.rs
- updated to polkadot 0.9.18 based
- https://blocksphere2020.atlassian.net/browse/MYR-2373
=> feat: updated to polkadot 0.9.18 based

Cargo.lock, node/Cargo.toml, node/src/chain_spec.rs, node/src/cli.rs, node/src/command.rs, node/src/lib.rs, node/src/rpc.rs, node/src/service.rs, pallets/server/Cargo.toml, pallets/server/src/lib.rs, pallets/server/src/mock.rs, pallets/server/src/tests.rs, pallets/server/src/types.rs, pallets/tipping/Cargo.toml, pallets/tipping/benchmarking/Cargo.toml, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/benchmarking/src/mock.rs, pallets/tipping/src/impl_tipping.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/mock.rs, pallets/tipping/src/types.rs, runtime/Cargo.toml, runtime/src/lib.rs
=> feat: bump version to 2.1.5

Cargo.lock, node/Cargo.toml, node/src/chain_spec.rs, node/src/cli.rs, node/src/command.rs, node/src/lib.rs, node/src/rpc.rs, node/src/service.rs, pallets/server/Cargo.toml, pallets/server/src/lib.rs, pallets/server/src/mock.rs, pallets/server/src/tests.rs, pallets/server/src/types.rs, pallets/tipping/Cargo.toml, pallets/tipping/benchmarking/Cargo.toml, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/benchmarking/src/mock.rs, pallets/tipping/src/impl_tipping.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/mock.rs, pallets/tipping/src/types.rs, runtime/Cargo.toml, runtime/src/lib.rs
update to polkadot v0.9.18
https://blocksphere2020.atlassian.net/browse/MYR-2373
=> feat: update to polkadot v0.9.18

Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, pallets/tipping/benchmarking/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
feat: update octopus dependencies to 0.9.18-2
https://blocksphere2020.atlassian.net/browse/MYR-2465
=> feat: update octopus dependencies to 0.9.18-2

pallets/server/src/functions.rs, pallets/server/src/impl_server.rs, pallets/server/src/interface.rs, pallets/server/src/lib.rs, pallets/server/src/migrations.rs, pallets/server/src/tests.rs, pallets/server/src/types.rs, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/src/functions.rs, pallets/tipping/src/migrations.rs, pallets/tipping/src/tests.rs, pallets/tipping/src/types.rs
- Change server id data type
[MYR-2441: Generate Server ID for deployment](https://blocksphere2020.atlassian.net/browse/MYR-2441)
=> fix: change server_id data type

Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/server/src/benchmarking.rs, pallets/server/src/functions.rs, pallets/server/src/impl_server.rs, pallets/server/src/lib.rs, pallets/server/src/migrations.rs, pallets/server/src/tests.rs, pallets/tipping/Cargo.toml, pallets/tipping/benchmarking/Cargo.toml, pallets/tipping/benchmarking/src/lib.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/migrations.rs, pallets/tipping/src/tests.rs, runtime/Cargo.toml, runtime/src/lib.rs
[MYR-2508: Tipping migration](https://blocksphere2020.atlassian.net/browse/MYR-2508)
=> fix: tipping migration

Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
=> chore: bump version to 2.2.0

.github/workflows/builder.yml, .github/workflows/tester.yml, .maintain/docker/Dockerfile, .maintain/docker/injected-binnary.Dockerfile, .maintain/pallet-weight-template.hbs, Cargo.lock, node/Cargo.toml, node/src/benchmarking.rs, node/src/chain_spec.rs, node/src/cli.rs, node/src/command.rs, node/src/main.rs, node/src/rpc.rs, node/src/service.rs, pallets/server/Cargo.toml, pallets/server/src/functions.rs, pallets/server/src/lib.rs, pallets/server/src/migrations.rs, pallets/server/src/mock.rs, pallets/server/src/tests.rs, pallets/server/src/weights.rs, pallets/tipping/Cargo.toml, pallets/tipping/src/functions.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/migrations.rs, pallets/tipping/src/mock.rs, pallets/tipping/src/tests.rs, pallets/tipping/src/weights.rs, runtime/Cargo.toml, runtime/src/lib.rs
feat: update node to polkadot 0.9.30
https://blocksphere2020.atlassian.net/browse/MYR-2807
=> feat: update node to polkadot 0.9.30

runtime/src/lib.rs
=> fix: octopus migration

pallets/tipping/src/benchmarking.rs, pallets/tipping/src/functions.rs, pallets/tipping/src/impl_tipping.rs, pallets/tipping/src/interface.rs, pallets/tipping/src/lib.rs, pallets/tipping/src/tests.rs, pallets/tipping/src/types.rs
=> fix: update reward balance storage

Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
=> chore: bump version to 2.3.1

pallets/tipping/src/functions.rs, pallets/tipping/src/impl_tipping.rs, pallets/tipping/src/tests.rs
=> fix: handle payment check with asset id

Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
=> chore: bump version to 2.3.2

pallets/server/src/lib.rs, pallets/tipping/src/benchmarking.rs
=> fix: fixed benchmarking

pallets/server/src/lib.rs, pallets/server/src/migrations.rs
=> fix: remove inactive server on pallet server storage

Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
=> chore: bump version to 2.3.3

.github/workflows/cicd.yaml
=> ci: fix release

.dockerignore, .github/workflows/cicd.yaml, .maintain/docker/Dockerfile, .maintain/docker/injected-binnary.Dockerfile, Cargo.lock, Cargo.toml, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, runtime/Cargo.toml
=> ci: fix release versioning

.github/workflows/cicd.yaml
=> ci: fix version file

.github/workflows/cicd.yaml
=> ci: fix illegal path

.github/workflows/cicd.yaml
=> ci: fix release path

.github/workflows/cicd.yaml
=> ci: added release plugin

.github/workflows/cicd.yaml
ci: fix release compute version
=> ci: fix release compute version

.github/PULL_REQUEST_TEMPLATE.md, .github/pull_request_template.md, .github/workflows/cicd.yaml
=> ci: fix release package name

.github/workflows/cicd.yaml
=> ci: move release path to root

.github/workflows/cicd.yaml, Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, runtime/Cargo.toml
=> chore: bump version to 2.3.4

pallets/server/src/lib.rs, pallets/server/src/migrations.rs
=> fix: server count migration

pallets/tipping/src/functions.rs, pallets/tipping/src/impl_tipping.rs, pallets/tipping/src/tests.rs
Fix pay_content
Change Test pay_content_with_myria , pay_content_with_assets , pay_content_with_escrow
already built for release
already tested using cargo test pay_content 
3 test successful, 1 failed
pay_content_with_insufficient_balance failed
Change has been commented
=> fix: content pay

Cargo.lock, node/Cargo.toml, pallets/server/Cargo.toml, pallets/tipping/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
=> chore: bump version to 2.3.6
